In [48]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, f1_score

In [49]:
heart = pd.read_csv('heart (1).csv')

In [50]:
heart

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [51]:
heart.shape

(303, 14)

In [52]:
heart.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [53]:
heart.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [54]:
heart.duplicated().sum()

np.int64(1)

In [55]:
heart[heart.duplicated()]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
164   38    1   2       138   175    0        1      173      0      0.0   

     slope  ca  thal  target  
164      2   4     2       1

In [56]:
heart.drop_duplicates(inplace=True)

In [57]:
# Outlier Detection
def remove_outliers(data, columns):
  for column in columns:
    if column in data.columns:
      Q1 = data[column].quantile(0.25)
      Q3 = data[column].quantile(0.75)
      IQR = Q3-Q1
      lower_bound = Q1-1.5*IQR
      upper_bound = Q3+1.5*IQR
      data = data[(data[column]>=lower_bound)&(data[column]<=upper_bound)]
  return data

In [58]:
data_without_outliers = remove_outliers(heart, heart.columns)

In [59]:
data_without_outliers.shape

(228, 14)

In [60]:
X = heart.drop(columns='target')
y = heart['target']

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 20, random_state = 42)

In [62]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [63]:
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)

LogisticRegression()

In [64]:
log_reg.coef_ # prints w1 to w13

array([[-0.00323421, -0.78098792,  0.81750641, -0.41429306, -0.19267639,
         0.06635282,  0.27245197,  0.49295398, -0.3976617 , -0.59040803,
         0.44278852, -0.78284391, -0.52070597]])

In [65]:
log_reg.intercept_

array([0.10130928])

In [66]:
y_pred = log_reg.predict(X_test_scaled)

In [67]:
y_pred

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [68]:
probs =log_reg.predict_proba(X_test_scaled)

In [69]:
probs

array([[0.97223837, 0.02776163],
       [0.769238  , 0.230762  ],
       [0.16603793, 0.83396207],
       [0.92492528, 0.07507472],
       [0.03865467, 0.96134533],
       [0.09999559, 0.90000441],
       [0.36696676, 0.63303324],
       [0.97238662, 0.02761338],
       [0.99246979, 0.00753021],
       [0.56136928, 0.43863072],
       [0.27821498, 0.72178502],
       [0.9448145 , 0.0551855 ],
       [0.09899675, 0.90100325],
       [0.89153442, 0.10846558],
       [0.0082524 , 0.9917476 ],
       [0.06755244, 0.93244756],
       [0.01063855, 0.98936145],
       [0.99593067, 0.00406933],
       [0.9928027 , 0.0071973 ],
       [0.98287596, 0.01712404]])

In [70]:
accuracy_score(y_test, y_pred)

0.9